### PR TITLE
Make the mod info header readable

### PR DESCRIPTION
**Pull request by ColonelGerdauf**
Unless I am misunderstanding something, there is no "modpack" here. This strange format makes it difficult for launchers to understand what is going on, thereby treating it as an arbitrary junk file.

### CODE REVIEW

**Review by glowredman — COMMENTED** [review]
It's intended to be like this, see https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/master/src/main/resources/mcmod.info. The "modList" property exists because you can have multiple mods in one jar, like e.g. ProjectRed does it.

**Comment by ColonelGerdauf** [comment]
image
Meanwhile, the other GTNH mods
image

**Comment by glowredman** [comment]
This looks like a bug/oversight in MMC/Prism then as [this format](https://github.com/MinecraftForge/FML/blob/1.7.10/src/main/java/cpw/mods/fml/common/MetadataCollection.java) isn't exactly new. This behaviour isn't exclusive to CMM either, many other GTNH mods use the modListVersion 2 format.

**Comment by Lyfts** [comment]
You don't need to change the format you can just remove the non curly brackets from the top and bottom as those shouldn't be there when using modListVersion 2 format.

**Comment by ColonelGerdauf** [comment]
Still, it is rather strange to make this kind of format universal, given that this is something that is expected to be used on an as-needed basis.

If a mod isn't a pack, there is no need for the format. If a mod becomes a pack, then the metadata can be changed to reflect that.

I should mention that Project Red is also a pack, and the metadata is read correctly. Out of all of the GTNH mods I have, this is the only one exhibiting such behaviour. So there is something specific about the metadata here that is not playing nicely with launchers.

**Comment by Lyfts** [comment]
There's really no reason to change the format.. if you revert to the old format and just remove the top and bottom bracket it will be read correctly by whatever launcher you're using.

**Comment by miozune** [comment]
Please restore placeholders like `${modId}`

**Comment by ColonelGerdauf** [comment]
Sorry about that. I clumsily copied it from a static source, and forgot the variables.

**Review by miozune — APPROVED** [review]

**Pull request merged**
